repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black"]
        language: system
        types: [python]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black
        args: ["--config", ".black"]
        language: system
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        name: flake8
        args: ["--config", ".flake8"]
        language: system
        types: [python]
