"""сchange organisation table

Revision ID: 67e30f32ea98
Revises: 4054cd02f49e
Create Date: 2025-04-29 13:23:27.887342

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "67e30f32ea98"
down_revision: Union[str, None] = "4054cd02f49e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
