"""Remove user_id from roles

Revision ID: f15eeb97b4b9
Revises: effef729f609
Create Date: 2025-04-17 13:54:47.114315

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f15eeb97b4b9"
down_revision: Union[str, None] = "effef729f609"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_constraint("roles_user_id_fkey", type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key("roles_user_id_fkey", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###
